# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

data_to_replicate:
{% if sql_flavour.upper() == 'S4' %}
  - base_table: acdoca
    load_frequency: "@hourly"
    cluster_details:
      columns: ["rclnt", "rbukrs"]

  - base_table: finsc_ld_cmp
    load_frequency: "@daily"

  - base_table: finsc_ledger_rep
    load_frequency: "@daily"

  - base_table: matdoc
    load_frequency: "@hourly"

  - base_table: prcd_elements
    load_frequency: "@hourly"

  - base_table: ckmlhd
    load_frequency: "@daily"

  - base_table: ckmlcr
    load_frequency: "@daily"

  - base_table: hrrp_node
    load_frequency: "@monthly"

  - base_table: hrrp_directory
    load_frequency: "@monthly"

  - base_table: hrrp_nodet
    load_frequency: "@monthly"

  - base_table: sethanahier0101
    load_frequency: "@monthly"

  - base_table: sethanahier0106
    load_frequency: "@monthly"

  - base_table: finsc_ledger
    load_frequency: "@yearly"

  - base_table: finsc_ledger_t
    load_frequency: "@yearly"
{% endif %}

{% if sql_flavour.upper() == 'ECC' %}
  - base_table: anla
    load_frequency: "@hourly"

  - base_table: ankt
    load_frequency: "@hourly"

  - base_table: faglflexa
    load_frequency: "@hourly"

  - base_table: konv
    load_frequency: "@daily"
    partition_details:
      column: "kdatu"
      partition_type: "time"
      time_grain: "day"
    cluster_details:
      columns: ["stunr"]

  - base_table: mseg
    load_frequency: "@hourly"

  - base_table: prps
    load_frequency: "@hourly"

  - base_table: vbuk
    load_frequency: "@hourly"

  - base_table: vbup
    load_frequency: "@hourly"

  - base_table: msfd
    load_frequency: "@weekly"

  - base_table: fagl_011pc
    load_frequency: "@monthly"

  - base_table: fagl_011qt
    load_frequency: "@monthly"

  - base_table: fagl_011zc
    load_frequency: "@monthly"
{% endif %}

# Common tables (always included)
  - base_table: adr6
    load_frequency: "@daily"

  - base_table: adrc
    load_frequency: "@daily"

  - base_table: bkpf
    load_frequency: "@hourly"
    partition_details:
      column: "budat"
      partition_type: "time"
      time_grain: "day"
    cluster_details:
      columns: ["bukrs", "gjahr"]

  - base_table: bseg
    load_frequency: "@hourly"
    cluster_details:
      columns: ["mandt", "bukrs", "gjahr"]

#################################################################################################
# PARTITIONED TABLES
  - base_table: Anand2
    load_frequency: "@daily"
    partition_details:
      column: "recordstamp"
      partition_type: "time"
      time_grain: "day"
    cluster_details:
      columns: ["col1", "col2", "col3"]

  - base_table: dfdf
    load_frequency: "0 */6 * * *"
    partition_details:
      column: "recordstamp"
      partition_type: "time"
      time_grain: "day"
    cluster_details:
      columns: ["vkorg"]

#################################################################################################
# NON-PARTITIONED TABLES
  - base_table: hjhj
    load_frequency: "@hourly"
    cluster_details:
      columns: ["werks", "lgort"]

  - base_table: jkjk
    load_frequency: "@hourly"

  - base_table: klkl
    load_frequency: "@hourly"

  - base_table: qwqw
    load_frequency: "@hourly"

  - base_table: wewe
    load_frequency: "@hourly"

  - base_table: erer
    load_frequency: "@hourly"

  - base_table: trtt
    load_frequency: "@daily"

  - base_table: tyty
    load_frequency: "@weekly"

  - base_table: yuyu
    load_frequency: "@weekly"

  - base_table: uiui
    load_frequency: "@weekly"

  - base_table: ioio
    load_frequency: "@weekly"
